-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (AuthenticatePayload(..), PageInfo(..), Proposal(..), RegisterPayload(..), UpdateProposalPayload(..), UpdateUserPayload(..), User(..), UsersConnection(..), UsersEdge(..))


type AuthenticatePayload
    = AuthenticatePayload


type PageInfo
    = PageInfo


type Proposal
    = Proposal


type RegisterPayload
    = RegisterPayload


type UpdateProposalPayload
    = UpdateProposalPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type UsersConnection
    = UsersConnection


type UsersEdge
    = UsersEdge
