-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (AuthenticatePayload(..), CreateProposalPayload(..), Proposal(..), ProposalsEdge(..), RegisterPayload(..), UpdateProposalPayload(..), UpdateUserPayload(..), User(..), UsersEdge(..))


type AuthenticatePayload
    = AuthenticatePayload


type CreateProposalPayload
    = CreateProposalPayload


type Proposal
    = Proposal


type ProposalsEdge
    = ProposalsEdge


type RegisterPayload
    = RegisterPayload


type UpdateProposalPayload
    = UpdateProposalPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type UsersEdge
    = UsersEdge
