-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Scalar exposing (Codecs, Cursor(..), Datetime(..), Id(..), JwtToken(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type Cursor
    = Cursor String


type Datetime
    = Datetime String


type Id
    = Id String


type JwtToken
    = JwtToken String


defineCodecs :
    { codecCursor : Codec valueCursor
    , codecDatetime : Codec valueDatetime
    , codecId : Codec valueId
    , codecJwtToken : Codec valueJwtToken
    }
    -> Codecs valueCursor valueDatetime valueId valueJwtToken
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueCursor valueDatetime valueId valueJwtToken
    ->
        { codecCursor : Codec valueCursor
        , codecDatetime : Codec valueDatetime
        , codecId : Codec valueId
        , codecJwtToken : Codec valueJwtToken
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueCursor valueDatetime valueId valueJwtToken
    = Codecs (RawCodecs valueCursor valueDatetime valueId valueJwtToken)


type alias RawCodecs valueCursor valueDatetime valueId valueJwtToken =
    { codecCursor : Codec valueCursor
    , codecDatetime : Codec valueDatetime
    , codecId : Codec valueId
    , codecJwtToken : Codec valueJwtToken
    }


defaultCodecs : RawCodecs Cursor Datetime Id JwtToken
defaultCodecs =
    { codecCursor =
        { encoder = \(Cursor raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Cursor
        }
    , codecDatetime =
        { encoder = \(Datetime raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Datetime
        }
    , codecId =
        { encoder = \(Id raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Id
        }
    , codecJwtToken =
        { encoder = \(JwtToken raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map JwtToken
        }
    }
