-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (Cursor, Datetime, Id, JwtToken, codecs)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Cursor =
    Api.Scalar.Cursor


type alias Datetime =
    Api.Scalar.Datetime


type alias Id =
    Api.Scalar.Id


type alias JwtToken =
    Api.Scalar.JwtToken


codecs : Api.Scalar.Codecs Cursor Datetime Id JwtToken
codecs =
    Api.Scalar.defineCodecs
        { codecCursor = defaultCodecs.codecCursor
        , codecDatetime = defaultCodecs.codecDatetime
        , codecId = defaultCodecs.codecId
        , codecJwtToken = defaultCodecs.codecJwtToken
        }
