-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PageInfo exposing (endCursor, hasNextPage, hasPreviousPage, startCursor)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| When paginating forwards, are there more items?
-}
hasNextPage : SelectionSet Bool Api.Object.PageInfo
hasNextPage =
    Object.selectionForField "Bool" "hasNextPage" [] Decode.bool


{-| When paginating backwards, are there more items?
-}
hasPreviousPage : SelectionSet Bool Api.Object.PageInfo
hasPreviousPage =
    Object.selectionForField "Bool" "hasPreviousPage" [] Decode.bool


{-| When paginating backwards, the cursor to continue.
-}
startCursor : SelectionSet (Maybe Api.ScalarCodecs.Cursor) Api.Object.PageInfo
startCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "startCursor" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)


{-| When paginating forwards, the cursor to continue.
-}
endCursor : SelectionSet (Maybe Api.ScalarCodecs.Cursor) Api.Object.PageInfo
endCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "endCursor" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)
